### PR TITLE
Add Sphinx documentation

### PR DESCRIPTION
**Pull request by rgreinho**
Adds Sphinx documentation to the project.

Drive-by:
- Adds a just task for the documentation.

### CODE REVIEW

**Comment by rgreinho** [comment]
@lalver1 This PR is a draft since it depends on #11. Once #11 is merged, I'll mark it as ready for review.

**Review by lalver1 — DISMISSED** [review]
Built the documentation 👍 but need to look into a few 'Title underline too short' warnings.

**Comment by rgreinho** [comment]
Thanks for the reminder @lalver1 !

I fixed the doctests to use the right syntax, I updated the Sphinx options to make it run in strict mode and disabled the `pydocstyle` rule which was conflicting.

**Review by lalver1 — APPROVED** [review]
👍

**Pull request merged**
